#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = python3 ~/.config/waybar/hypr-workspace-labels.py
exec-once = hypridle
exec-once = mako         # Notification Daemon
exec-once = blueberry-tray
exec-once = nm-applet
exec-once = swww-daemon  # Wallpaper Daemon
exec-once = systemctl --user start hyprpolkitagent
