exec-once = waybar 
exec-once = hypridle
exec-once = mako         # Notification Daemon
exec-once = blueberry-tray
exec-once = nm-applet
exec-once = swww-daemon  # Wallpaper Daemon
exec-once = systemctl --user start hyprpolkitagent
