###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus
$menu = fuzzel

$cursorTheme = Capitaine-cursors

$mainMod = SUPER

################
### MONITORS ###
################

monitor = ,preferred,auto,auto

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = HYPRCURSOR_THEME,Adwaita
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24
