############################
### HYPRLAND CONFIG FILE ###
############################

# Colors (theme)
source = ~/.config/hypr/colors.conf

# Variables, programs, monitors, and environment
source = ~/.config/hypr/core/variables.conf

# Autostart applications
source = ~/.config/hypr/core/autostart.conf

# Appearance (general, decoration, animations, layouts)
source = ~/.config/hypr/core/appearance.conf

# Input settings and gestures
source = ~/.config/hypr/core/input.conf

# Keybindings
source = ~/.config/hypr/core/keybindings.conf

# Window rules and workspace settings
source = ~/.config/hypr/core/windowrules.conf
