# Core Colors
background            #11140f
foreground            #e1e4da
selection_foreground  #a5d395
selection_background  #12380b
cursor                #a5d395
cursor_text_color     #11140f

# Regular Colors
color0  #11140f
color1  #ffb4ab
color2  #a5d395
color3  #a0cfd2
color4  #c1efaf
color5  #d7e8cc
color6  #bbcbb1
color7  #e1e4da

# Bright Colors
color8  #363a34
color9  #ffb4ab
color10 #a5d395
color11 #a0cfd2
color12 #c1efaf
color13 #d7e8cc 
color14 #bbcbb1
color15 #e1e4da
