# Core Colors
background            #161217
foreground            #e9e0e7
selection_foreground  #e4b7f3
selection_background  #442253
cursor                #e4b7f3
cursor_text_color     #161217

# Regular Colors
color0  #161217
color1  #ffb4ab
color2  #e4b7f3
color3  #f5b7b5
color4  #f8d8ff
color5  #f1dcf4
color6  #d4c0d7
color7  #e9e0e7

# Bright Colors
color8  #3d373d
color9  #ffb4ab
color10 #e4b7f3
color11 #f5b7b5
color12 #f8d8ff
color13 #f1dcf4 
color14 #d4c0d7
color15 #e9e0e7
